version: '3.1'

services:

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata57:/var/lib/mysql

  mysql_8:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    command: mysqld --sql_mode=""
    volumes:
      - dbdata8:/var/lib/mysql

  conqueso:
    build: .
    restart: always
    ports:
      - "8080:8080"

volumes:
  dbdata57:
  dbdata8:
